packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  '@openapitools/openapi-generator-cli': true
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

# temp until eslint-plugin-react supports eslint v10
patchedDependencies:
  eslint-plugin-react@7.37.5: patches/eslint-plugin-react@7.37.5.patch
