/* tslint:disable */
/* eslint-disable */
/**
 * Ticketing Service API
 * Laboratory experiment ticketing service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequest,
    GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequestFromJSON,
    GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequestToJSON,
} from '../models/GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequest';
import {
    type GithubComHoshinaDevTicketingServiceInternalDtoErrorResponse,
    GithubComHoshinaDevTicketingServiceInternalDtoErrorResponseFromJSON,
    GithubComHoshinaDevTicketingServiceInternalDtoErrorResponseToJSON,
} from '../models/GithubComHoshinaDevTicketingServiceInternalDtoErrorResponse';
import {
    type GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse,
    GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponseFromJSON,
    GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponseToJSON,
} from '../models/GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse';

export interface ApiV1TicketsIdExperimentTemplatesGetRequest {
    id: string;
}

export interface ApiV1TicketsIdExperimentTemplatesPostRequest {
    id: string;
    body: GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequest;
}

export interface ApiV1TicketsIdExperimentTemplatesTemplateIdDeleteRequest {
    id: string;
    templateId: string;
}

/**
 * 
 */
export class ExperimentTemplatesApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiV1TicketsIdExperimentTemplatesGet without sending the request
     */
    async apiV1TicketsIdExperimentTemplatesGetRequestOpts(requestParameters: ApiV1TicketsIdExperimentTemplatesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1TicketsIdExperimentTemplatesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/tickets/{id}/experiment-templates`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List experiment templates on a ticket
     */
    async apiV1TicketsIdExperimentTemplatesGetRaw(requestParameters: ApiV1TicketsIdExperimentTemplatesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse>>> {
        const requestOptions = await this.apiV1TicketsIdExperimentTemplatesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponseFromJSON));
    }

    /**
     * List experiment templates on a ticket
     */
    async apiV1TicketsIdExperimentTemplatesGet(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse>> {
        const response = await this.apiV1TicketsIdExperimentTemplatesGetRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiV1TicketsIdExperimentTemplatesPost without sending the request
     */
    async apiV1TicketsIdExperimentTemplatesPostRequestOpts(requestParameters: ApiV1TicketsIdExperimentTemplatesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1TicketsIdExperimentTemplatesPost().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiV1TicketsIdExperimentTemplatesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/tickets/{id}/experiment-templates`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequestToJSON(requestParameters['body']),
        };
    }

    /**
     * Add an experiment template to a ticket
     */
    async apiV1TicketsIdExperimentTemplatesPostRaw(requestParameters: ApiV1TicketsIdExperimentTemplatesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse>> {
        const requestOptions = await this.apiV1TicketsIdExperimentTemplatesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponseFromJSON(jsonValue));
    }

    /**
     * Add an experiment template to a ticket
     */
    async apiV1TicketsIdExperimentTemplatesPost(id: string, body: GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse> {
        const response = await this.apiV1TicketsIdExperimentTemplatesPostRaw({ id: id, body: body }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiV1TicketsIdExperimentTemplatesTemplateIdDelete without sending the request
     */
    async apiV1TicketsIdExperimentTemplatesTemplateIdDeleteRequestOpts(requestParameters: ApiV1TicketsIdExperimentTemplatesTemplateIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1TicketsIdExperimentTemplatesTemplateIdDelete().'
            );
        }

        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling apiV1TicketsIdExperimentTemplatesTemplateIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/tickets/{id}/experiment-templates/{templateId}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{templateId}', encodeURIComponent(String(requestParameters['templateId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove an experiment template from a ticket
     */
    async apiV1TicketsIdExperimentTemplatesTemplateIdDeleteRaw(requestParameters: ApiV1TicketsIdExperimentTemplatesTemplateIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiV1TicketsIdExperimentTemplatesTemplateIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove an experiment template from a ticket
     */
    async apiV1TicketsIdExperimentTemplatesTemplateIdDelete(id: string, templateId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1TicketsIdExperimentTemplatesTemplateIdDeleteRaw({ id: id, templateId: templateId }, initOverrides);
    }

}
