/* tslint:disable */
/* eslint-disable */
/**
 * Ticketing Service API
 * Laboratory experiment ticketing service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequest,
    GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequestFromJSON,
    GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequestToJSON,
} from '../models/GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequest';
import {
    type GithubComHoshinaDevTicketingServiceInternalDtoErrorResponse,
    GithubComHoshinaDevTicketingServiceInternalDtoErrorResponseFromJSON,
    GithubComHoshinaDevTicketingServiceInternalDtoErrorResponseToJSON,
} from '../models/GithubComHoshinaDevTicketingServiceInternalDtoErrorResponse';
import {
    type GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse,
    GithubComHoshinaDevTicketingServiceInternalDtoTicketResponseFromJSON,
    GithubComHoshinaDevTicketingServiceInternalDtoTicketResponseToJSON,
} from '../models/GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse';
import {
    type GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequest,
    GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequestFromJSON,
    GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequestToJSON,
} from '../models/GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequest';

export interface ApiV1TicketsGetRequest {
    userId?: string;
    organizationId?: string;
    status?: string;
    sortBy?: string;
    sortDir?: string;
}

export interface ApiV1TicketsIdDeleteRequest {
    id: string;
}

export interface ApiV1TicketsIdGetRequest {
    id: string;
}

export interface ApiV1TicketsIdStatusPatchRequest {
    id: string;
    body: GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequest;
}

export interface ApiV1TicketsPostRequest {
    body: GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequest;
}

/**
 * 
 */
export class TicketsApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiV1TicketsGet without sending the request
     */
    async apiV1TicketsGetRequestOpts(requestParameters: ApiV1TicketsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['user_id'] = requestParameters['userId'];
        }

        if (requestParameters['organizationId'] != null) {
            queryParameters['organization_id'] = requestParameters['organizationId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sort_by'] = requestParameters['sortBy'];
        }

        if (requestParameters['sortDir'] != null) {
            queryParameters['sort_dir'] = requestParameters['sortDir'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/tickets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List tickets
     */
    async apiV1TicketsGetRaw(requestParameters: ApiV1TicketsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse>>> {
        const requestOptions = await this.apiV1TicketsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GithubComHoshinaDevTicketingServiceInternalDtoTicketResponseFromJSON));
    }

    /**
     * List tickets
     */
    async apiV1TicketsGet(userId?: string, organizationId?: string, status?: string, sortBy?: string, sortDir?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse>> {
        const response = await this.apiV1TicketsGetRaw({ userId: userId, organizationId: organizationId, status: status, sortBy: sortBy, sortDir: sortDir }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiV1TicketsIdDelete without sending the request
     */
    async apiV1TicketsIdDeleteRequestOpts(requestParameters: ApiV1TicketsIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1TicketsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/tickets/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a ticket
     */
    async apiV1TicketsIdDeleteRaw(requestParameters: ApiV1TicketsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiV1TicketsIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a ticket
     */
    async apiV1TicketsIdDelete(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1TicketsIdDeleteRaw({ id: id }, initOverrides);
    }

    /**
     * Creates request options for apiV1TicketsIdGet without sending the request
     */
    async apiV1TicketsIdGetRequestOpts(requestParameters: ApiV1TicketsIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1TicketsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/tickets/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a ticket by ID
     */
    async apiV1TicketsIdGetRaw(requestParameters: ApiV1TicketsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse>> {
        const requestOptions = await this.apiV1TicketsIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GithubComHoshinaDevTicketingServiceInternalDtoTicketResponseFromJSON(jsonValue));
    }

    /**
     * Get a ticket by ID
     */
    async apiV1TicketsIdGet(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse> {
        const response = await this.apiV1TicketsIdGetRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiV1TicketsIdStatusPatch without sending the request
     */
    async apiV1TicketsIdStatusPatchRequestOpts(requestParameters: ApiV1TicketsIdStatusPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1TicketsIdStatusPatch().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiV1TicketsIdStatusPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/tickets/{id}/status`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequestToJSON(requestParameters['body']),
        };
    }

    /**
     * Transition ticket status
     */
    async apiV1TicketsIdStatusPatchRaw(requestParameters: ApiV1TicketsIdStatusPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse>> {
        const requestOptions = await this.apiV1TicketsIdStatusPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GithubComHoshinaDevTicketingServiceInternalDtoTicketResponseFromJSON(jsonValue));
    }

    /**
     * Transition ticket status
     */
    async apiV1TicketsIdStatusPatch(id: string, body: GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse> {
        const response = await this.apiV1TicketsIdStatusPatchRaw({ id: id, body: body }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiV1TicketsPost without sending the request
     */
    async apiV1TicketsPostRequestOpts(requestParameters: ApiV1TicketsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiV1TicketsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/tickets`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequestToJSON(requestParameters['body']),
        };
    }

    /**
     * Create a ticket
     */
    async apiV1TicketsPostRaw(requestParameters: ApiV1TicketsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse>> {
        const requestOptions = await this.apiV1TicketsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GithubComHoshinaDevTicketingServiceInternalDtoTicketResponseFromJSON(jsonValue));
    }

    /**
     * Create a ticket
     */
    async apiV1TicketsPost(body: GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse> {
        const response = await this.apiV1TicketsPostRaw({ body: body }, initOverrides);
        return await response.value();
    }

}
