/* tslint:disable */
/* eslint-disable */
/**
 * Customer API
 * A simple REST API for managing users and organizations
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AddMemberRequest,
    AddMemberRequestFromJSON,
    AddMemberRequestToJSON,
} from '../models/AddMemberRequest';
import {
    type CreateOrganizationRequest,
    CreateOrganizationRequestFromJSON,
    CreateOrganizationRequestToJSON,
} from '../models/CreateOrganizationRequest';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type GetOrganizationsByIDsRequest,
    GetOrganizationsByIDsRequestFromJSON,
    GetOrganizationsByIDsRequestToJSON,
} from '../models/GetOrganizationsByIDsRequest';
import {
    type OrganizationCoord,
    OrganizationCoordFromJSON,
    OrganizationCoordToJSON,
} from '../models/OrganizationCoord';
import {
    type OrganizationResponse,
    OrganizationResponseFromJSON,
    OrganizationResponseToJSON,
} from '../models/OrganizationResponse';
import {
    type SetRoleRequest,
    SetRoleRequestFromJSON,
    SetRoleRequestToJSON,
} from '../models/SetRoleRequest';
import {
    type UpdateOrganizationRequest,
    UpdateOrganizationRequestFromJSON,
    UpdateOrganizationRequestToJSON,
} from '../models/UpdateOrganizationRequest';
import {
    type UserWithRoleResponse,
    UserWithRoleResponseFromJSON,
    UserWithRoleResponseToJSON,
} from '../models/UserWithRoleResponse';

export interface OrganizationsBatchPostRequest {
    request: GetOrganizationsByIDsRequest;
}

export interface OrganizationsIdDeleteRequest {
    id: string;
}

export interface OrganizationsIdGetRequest {
    id: string;
}

export interface OrganizationsIdMembersGetRequest {
    id: string;
}

export interface OrganizationsIdMembersPostRequest {
    id: string;
    req: AddMemberRequest;
}

export interface OrganizationsIdMembersUserIdDeleteRequest {
    id: string;
    userId: string;
}

export interface OrganizationsIdMembersUserIdPatchRequest {
    id: string;
    userId: string;
    req: SetRoleRequest;
}

export interface OrganizationsIdPatchRequest {
    id: string;
    organization: UpdateOrganizationRequest;
}

export interface OrganizationsPostRequest {
    organization: CreateOrganizationRequest;
}

export interface OrganizationsSearchGetRequest {
    q: string;
    limit?: number;
}

/**
 * 
 */
export class OrganizationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for organizationsBatchPost without sending the request
     */
    async organizationsBatchPostRequestOpts(requestParameters: OrganizationsBatchPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling organizationsBatchPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/organizations/batch`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetOrganizationsByIDsRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Get multiple organizations by their UUIDs in a single request
     * Get organizations by multiple IDs (batch)
     */
    async organizationsBatchPostRaw(requestParameters: OrganizationsBatchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrganizationResponse>>> {
        const requestOptions = await this.organizationsBatchPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrganizationResponseFromJSON));
    }

    /**
     * Get multiple organizations by their UUIDs in a single request
     * Get organizations by multiple IDs (batch)
     */
    async organizationsBatchPost(request: GetOrganizationsByIDsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrganizationResponse>> {
        const response = await this.organizationsBatchPostRaw({ request: request }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for organizationsCoordinatesGet without sending the request
     */
    async organizationsCoordinatesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/organizations/coordinates`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get ID and coordinates of all organizations
     * Get all organization coordinates
     */
    async organizationsCoordinatesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrganizationCoord>>> {
        const requestOptions = await this.organizationsCoordinatesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrganizationCoordFromJSON));
    }

    /**
     * Get ID and coordinates of all organizations
     * Get all organization coordinates
     */
    async organizationsCoordinatesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrganizationCoord>> {
        const response = await this.organizationsCoordinatesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for organizationsGet without sending the request
     */
    async organizationsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/organizations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a list of all organizations
     * Get all organizations
     */
    async organizationsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrganizationResponse>>> {
        const requestOptions = await this.organizationsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrganizationResponseFromJSON));
    }

    /**
     * Get a list of all organizations
     * Get all organizations
     */
    async organizationsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrganizationResponse>> {
        const response = await this.organizationsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for organizationsIdDelete without sending the request
     */
    async organizationsIdDeleteRequestOpts(requestParameters: OrganizationsIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling organizationsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/organizations/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Soft delete an organization by ID
     * Delete an organization
     */
    async organizationsIdDeleteRaw(requestParameters: OrganizationsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.organizationsIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Soft delete an organization by ID
     * Delete an organization
     */
    async organizationsIdDelete(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.organizationsIdDeleteRaw({ id: id }, initOverrides);
    }

    /**
     * Creates request options for organizationsIdGet without sending the request
     */
    async organizationsIdGetRequestOpts(requestParameters: OrganizationsIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling organizationsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/organizations/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single organization by their ID
     * Get an organization by ID
     */
    async organizationsIdGetRaw(requestParameters: OrganizationsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationResponse>> {
        const requestOptions = await this.organizationsIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationResponseFromJSON(jsonValue));
    }

    /**
     * Get a single organization by their ID
     * Get an organization by ID
     */
    async organizationsIdGet(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationResponse> {
        const response = await this.organizationsIdGetRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for organizationsIdMembersGet without sending the request
     */
    async organizationsIdMembersGetRequestOpts(requestParameters: OrganizationsIdMembersGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling organizationsIdMembersGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/organizations/{id}/members`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all users that belong to an organization
     * Get members of an organization
     */
    async organizationsIdMembersGetRaw(requestParameters: OrganizationsIdMembersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserWithRoleResponse>>> {
        const requestOptions = await this.organizationsIdMembersGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserWithRoleResponseFromJSON));
    }

    /**
     * Get all users that belong to an organization
     * Get members of an organization
     */
    async organizationsIdMembersGet(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserWithRoleResponse>> {
        const response = await this.organizationsIdMembersGetRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for organizationsIdMembersPost without sending the request
     */
    async organizationsIdMembersPostRequestOpts(requestParameters: OrganizationsIdMembersPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling organizationsIdMembersPost().'
            );
        }

        if (requestParameters['req'] == null) {
            throw new runtime.RequiredError(
                'req',
                'Required parameter "req" was null or undefined when calling organizationsIdMembersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/organizations/{id}/members`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddMemberRequestToJSON(requestParameters['req']),
        };
    }

    /**
     * Add an existing user to an organization with an optional manager role
     * Add a member to an organization
     */
    async organizationsIdMembersPostRaw(requestParameters: OrganizationsIdMembersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.organizationsIdMembersPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add an existing user to an organization with an optional manager role
     * Add a member to an organization
     */
    async organizationsIdMembersPost(id: string, req: AddMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.organizationsIdMembersPostRaw({ id: id, req: req }, initOverrides);
    }

    /**
     * Creates request options for organizationsIdMembersUserIdDelete without sending the request
     */
    async organizationsIdMembersUserIdDeleteRequestOpts(requestParameters: OrganizationsIdMembersUserIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling organizationsIdMembersUserIdDelete().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling organizationsIdMembersUserIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/organizations/{id}/members/{user_id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove a member from an organization
     */
    async organizationsIdMembersUserIdDeleteRaw(requestParameters: OrganizationsIdMembersUserIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.organizationsIdMembersUserIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a member from an organization
     */
    async organizationsIdMembersUserIdDelete(id: string, userId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.organizationsIdMembersUserIdDeleteRaw({ id: id, userId: userId }, initOverrides);
    }

    /**
     * Creates request options for organizationsIdMembersUserIdPatch without sending the request
     */
    async organizationsIdMembersUserIdPatchRequestOpts(requestParameters: OrganizationsIdMembersUserIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling organizationsIdMembersUserIdPatch().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling organizationsIdMembersUserIdPatch().'
            );
        }

        if (requestParameters['req'] == null) {
            throw new runtime.RequiredError(
                'req',
                'Required parameter "req" was null or undefined when calling organizationsIdMembersUserIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/organizations/{id}/members/{user_id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: SetRoleRequestToJSON(requestParameters['req']),
        };
    }

    /**
     * Update a member\'s role within an organization
     */
    async organizationsIdMembersUserIdPatchRaw(requestParameters: OrganizationsIdMembersUserIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.organizationsIdMembersUserIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update a member\'s role within an organization
     */
    async organizationsIdMembersUserIdPatch(id: string, userId: string, req: SetRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.organizationsIdMembersUserIdPatchRaw({ id: id, userId: userId, req: req }, initOverrides);
    }

    /**
     * Creates request options for organizationsIdPatch without sending the request
     */
    async organizationsIdPatchRequestOpts(requestParameters: OrganizationsIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling organizationsIdPatch().'
            );
        }

        if (requestParameters['organization'] == null) {
            throw new runtime.RequiredError(
                'organization',
                'Required parameter "organization" was null or undefined when calling organizationsIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/organizations/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateOrganizationRequestToJSON(requestParameters['organization']),
        };
    }

    /**
     * Update an existing organization by ID (partial updates supported)
     * Update an organization
     */
    async organizationsIdPatchRaw(requestParameters: OrganizationsIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationResponse>> {
        const requestOptions = await this.organizationsIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationResponseFromJSON(jsonValue));
    }

    /**
     * Update an existing organization by ID (partial updates supported)
     * Update an organization
     */
    async organizationsIdPatch(id: string, organization: UpdateOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationResponse> {
        const response = await this.organizationsIdPatchRaw({ id: id, organization: organization }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for organizationsPost without sending the request
     */
    async organizationsPostRequestOpts(requestParameters: OrganizationsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['organization'] == null) {
            throw new runtime.RequiredError(
                'organization',
                'Required parameter "organization" was null or undefined when calling organizationsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/organizations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrganizationRequestToJSON(requestParameters['organization']),
        };
    }

    /**
     * Create a new organization with name, location, and optional details
     * Create a new organization
     */
    async organizationsPostRaw(requestParameters: OrganizationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationResponse>> {
        const requestOptions = await this.organizationsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationResponseFromJSON(jsonValue));
    }

    /**
     * Create a new organization with name, location, and optional details
     * Create a new organization
     */
    async organizationsPost(organization: CreateOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationResponse> {
        const response = await this.organizationsPostRaw({ organization: organization }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for organizationsSearchGet without sending the request
     */
    async organizationsSearchGetRequestOpts(requestParameters: OrganizationsSearchGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling organizationsSearchGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/organizations/search`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Search organizations by name using ILIKE query
     * Search organizations
     */
    async organizationsSearchGetRaw(requestParameters: OrganizationsSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrganizationResponse>>> {
        const requestOptions = await this.organizationsSearchGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrganizationResponseFromJSON));
    }

    /**
     * Search organizations by name using ILIKE query
     * Search organizations
     */
    async organizationsSearchGet(q: string, limit?: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrganizationResponse>> {
        const response = await this.organizationsSearchGetRaw({ q: q, limit: limit }, initOverrides);
        return await response.value();
    }

}
