/* tslint:disable */
/* eslint-disable */
/**
 * Customer API
 * A simple REST API for managing users and organizations
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateUserRequest,
    CreateUserRequestFromJSON,
    CreateUserRequestToJSON,
} from '../models/CreateUserRequest';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type UpdateUserRequest,
    UpdateUserRequestFromJSON,
    UpdateUserRequestToJSON,
} from '../models/UpdateUserRequest';
import {
    type UserDetailResponse,
    UserDetailResponseFromJSON,
    UserDetailResponseToJSON,
} from '../models/UserDetailResponse';
import {
    type UserMembershipResponse,
    UserMembershipResponseFromJSON,
    UserMembershipResponseToJSON,
} from '../models/UserMembershipResponse';
import {
    type UserResponse,
    UserResponseFromJSON,
    UserResponseToJSON,
} from '../models/UserResponse';

export interface UsersEmailEmailGetRequest {
    email: string;
}

export interface UsersIdIdDeleteRequest {
    id: string;
}

export interface UsersIdIdGetRequest {
    id: string;
}

export interface UsersIdIdOrganizationsGetRequest {
    id: string;
}

export interface UsersIdIdPatchRequest {
    id: string;
    user: UpdateUserRequest;
}

export interface UsersPostRequest {
    user: CreateUserRequest;
}

export interface UsersSearchGetRequest {
    q: string;
    limit?: number;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Creates request options for usersEmailEmailGet without sending the request
     */
    async usersEmailEmailGetRequestOpts(requestParameters: UsersEmailEmailGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling usersEmailEmailGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/email/{email}`;
        urlPath = urlPath.replace('{email}', encodeURIComponent(String(requestParameters['email'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single user by their email address
     * Get a user by email
     */
    async usersEmailEmailGetRaw(requestParameters: UsersEmailEmailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserDetailResponse>> {
        const requestOptions = await this.usersEmailEmailGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserDetailResponseFromJSON(jsonValue));
    }

    /**
     * Get a single user by their email address
     * Get a user by email
     */
    async usersEmailEmailGet(email: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserDetailResponse> {
        const response = await this.usersEmailEmailGetRaw({ email: email }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersGet without sending the request
     */
    async usersGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a list of all users
     * Get all users
     */
    async usersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserResponse>>> {
        const requestOptions = await this.usersGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserResponseFromJSON));
    }

    /**
     * Returns a list of all users
     * Get all users
     */
    async usersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserResponse>> {
        const response = await this.usersGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersIdIdDelete without sending the request
     */
    async usersIdIdDeleteRequestOpts(requestParameters: UsersIdIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling usersIdIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/id/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Soft delete a user by ID
     * Delete a user
     */
    async usersIdIdDeleteRaw(requestParameters: UsersIdIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.usersIdIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Soft delete a user by ID
     * Delete a user
     */
    async usersIdIdDelete(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.usersIdIdDeleteRaw({ id: id }, initOverrides);
    }

    /**
     * Creates request options for usersIdIdGet without sending the request
     */
    async usersIdIdGetRequestOpts(requestParameters: UsersIdIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling usersIdIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/id/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single user by their UUID
     * Get a user by ID
     */
    async usersIdIdGetRaw(requestParameters: UsersIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserDetailResponse>> {
        const requestOptions = await this.usersIdIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserDetailResponseFromJSON(jsonValue));
    }

    /**
     * Get a single user by their UUID
     * Get a user by ID
     */
    async usersIdIdGet(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserDetailResponse> {
        const response = await this.usersIdIdGetRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersIdIdOrganizationsGet without sending the request
     */
    async usersIdIdOrganizationsGetRequestOpts(requestParameters: UsersIdIdOrganizationsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling usersIdIdOrganizationsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/id/{id}/organizations`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all organizations a user belongs to with their role
     * Get a user\'s organizations
     */
    async usersIdIdOrganizationsGetRaw(requestParameters: UsersIdIdOrganizationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserMembershipResponse>>> {
        const requestOptions = await this.usersIdIdOrganizationsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserMembershipResponseFromJSON));
    }

    /**
     * Get all organizations a user belongs to with their role
     * Get a user\'s organizations
     */
    async usersIdIdOrganizationsGet(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserMembershipResponse>> {
        const response = await this.usersIdIdOrganizationsGetRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersIdIdPatch without sending the request
     */
    async usersIdIdPatchRequestOpts(requestParameters: UsersIdIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling usersIdIdPatch().'
            );
        }

        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersIdIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/id/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateUserRequestToJSON(requestParameters['user']),
        };
    }

    /**
     * Update an existing user by ID (partial updates supported)
     * Update a user
     */
    async usersIdIdPatchRaw(requestParameters: UsersIdIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        const requestOptions = await this.usersIdIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * Update an existing user by ID (partial updates supported)
     * Update a user
     */
    async usersIdIdPatch(id: string, user: UpdateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse> {
        const response = await this.usersIdIdPatchRaw({ id: id, user: user }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersPost without sending the request
     */
    async usersPostRequestOpts(requestParameters: UsersPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUserRequestToJSON(requestParameters['user']),
        };
    }

    /**
     * Create a new user with email, name, organization, and optional details
     * Create a new user
     */
    async usersPostRaw(requestParameters: UsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        const requestOptions = await this.usersPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * Create a new user with email, name, organization, and optional details
     * Create a new user
     */
    async usersPost(user: CreateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse> {
        const response = await this.usersPostRaw({ user: user }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersSearchGet without sending the request
     */
    async usersSearchGetRequestOpts(requestParameters: UsersSearchGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling usersSearchGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/search`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Search users by name or email using ILIKE query
     * Search users
     */
    async usersSearchGetRaw(requestParameters: UsersSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserResponse>>> {
        const requestOptions = await this.usersSearchGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserResponseFromJSON));
    }

    /**
     * Search users by name or email using ILIKE query
     * Search users
     */
    async usersSearchGet(q: string, limit?: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserResponse>> {
        const response = await this.usersSearchGetRaw({ q: q, limit: limit }, initOverrides);
        return await response.value();
    }

}
