/* tslint:disable */
/* eslint-disable */
/**
 * Ticketing Service API
 * Laboratory experiment ticketing service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse } from './GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse';
import {
    GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponseFromJSON,
    GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponseFromJSONTyped,
    GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponseToJSON,
    GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponseToJSONTyped,
} from './GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse';

/**
 * 
 * @export
 * @interface GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse
 */
export interface GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse {
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse
     */
    closedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse
     */
    closedReason?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse
     */
    experimentStartedAt?: string;
    /**
     * 
     * @type {GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse
     */
    experimentTemplate?: GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse;
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse
     */
    organizationId?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse
     */
    resultsSubmittedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse
     */
    sampleReceivedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse
     */
    userId?: string;
}

/**
 * Check if a given object implements the GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse interface.
 */
export function instanceOfGithubComHoshinaDevTicketingServiceInternalDtoTicketResponse(value: object): value is GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse {
    return true;
}

export function GithubComHoshinaDevTicketingServiceInternalDtoTicketResponseFromJSON(json: any): GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse {
    return GithubComHoshinaDevTicketingServiceInternalDtoTicketResponseFromJSONTyped(json, false);
}

export function GithubComHoshinaDevTicketingServiceInternalDtoTicketResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'closedAt': json['closed_at'] == null ? undefined : json['closed_at'],
        'closedReason': json['closed_reason'] == null ? undefined : json['closed_reason'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'experimentStartedAt': json['experiment_started_at'] == null ? undefined : json['experiment_started_at'],
        'experimentTemplate': json['experiment_template'] == null ? undefined : GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponseFromJSON(json['experiment_template']),
        'id': json['id'] == null ? undefined : json['id'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'resultsSubmittedAt': json['results_submitted_at'] == null ? undefined : json['results_submitted_at'],
        'sampleReceivedAt': json['sample_received_at'] == null ? undefined : json['sample_received_at'],
        'status': json['status'] == null ? undefined : json['status'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function GithubComHoshinaDevTicketingServiceInternalDtoTicketResponseToJSON(json: any): GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse {
    return GithubComHoshinaDevTicketingServiceInternalDtoTicketResponseToJSONTyped(json, false);
}

export function GithubComHoshinaDevTicketingServiceInternalDtoTicketResponseToJSONTyped(value?: GithubComHoshinaDevTicketingServiceInternalDtoTicketResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'closed_at': value['closedAt'],
        'closed_reason': value['closedReason'],
        'created_at': value['createdAt'],
        'experiment_started_at': value['experimentStartedAt'],
        'experiment_template': GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponseToJSON(value['experimentTemplate']),
        'id': value['id'],
        'organization_id': value['organizationId'],
        'results_submitted_at': value['resultsSubmittedAt'],
        'sample_received_at': value['sampleReceivedAt'],
        'status': value['status'],
        'updated_at': value['updatedAt'],
        'user_id': value['userId'],
    };
}

