/* tslint:disable */
/* eslint-disable */
/**
 * Ticketing Service API
 * Laboratory experiment ticketing service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse
 */
export interface GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse {
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse
     */
    experimentTemplateId?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse
     */
    ticketId?: string;
}

/**
 * Check if a given object implements the GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse interface.
 */
export function instanceOfGithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse(value: object): value is GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse {
    return true;
}

export function GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponseFromJSON(json: any): GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse {
    return GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponseFromJSONTyped(json, false);
}

export function GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'experimentTemplateId': json['experiment_template_id'] == null ? undefined : json['experiment_template_id'],
        'id': json['id'] == null ? undefined : json['id'],
        'ticketId': json['ticket_id'] == null ? undefined : json['ticket_id'],
    };
}

export function GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponseToJSON(json: any): GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse {
    return GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponseToJSONTyped(json, false);
}

export function GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponseToJSONTyped(value?: GithubComHoshinaDevTicketingServiceInternalDtoTicketExperimentTemplateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'experiment_template_id': value['experimentTemplateId'],
        'id': value['id'],
        'ticket_id': value['ticketId'],
    };
}

