/* tslint:disable */
/* eslint-disable */
/**
 * Ticketing Service API
 * Laboratory experiment ticketing service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequest
 */
export interface GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequest {
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequest
     */
    experimentTemplateId: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequest
     */
    organizationId: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequest
     */
    userId: string;
}

/**
 * Check if a given object implements the GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequest interface.
 */
export function instanceOfGithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequest(value: object): value is GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequest {
    if (!('experimentTemplateId' in value) || value['experimentTemplateId'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequestFromJSON(json: any): GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequest {
    return GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequestFromJSONTyped(json, false);
}

export function GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'experimentTemplateId': json['experiment_template_id'],
        'organizationId': json['organization_id'],
        'userId': json['user_id'],
    };
}

export function GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequestToJSON(json: any): GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequest {
    return GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequestToJSONTyped(json, false);
}

export function GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequestToJSONTyped(value?: GithubComHoshinaDevTicketingServiceInternalDtoCreateTicketRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'experiment_template_id': value['experimentTemplateId'],
        'organization_id': value['organizationId'],
        'user_id': value['userId'],
    };
}

