/* tslint:disable */
/* eslint-disable */
/**
 * Ticketing Service API
 * Laboratory experiment ticketing service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GithubComHoshinaDevTicketingServiceInternalDtoErrorResponse
 */
export interface GithubComHoshinaDevTicketingServiceInternalDtoErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoErrorResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the GithubComHoshinaDevTicketingServiceInternalDtoErrorResponse interface.
 */
export function instanceOfGithubComHoshinaDevTicketingServiceInternalDtoErrorResponse(value: object): value is GithubComHoshinaDevTicketingServiceInternalDtoErrorResponse {
    return true;
}

export function GithubComHoshinaDevTicketingServiceInternalDtoErrorResponseFromJSON(json: any): GithubComHoshinaDevTicketingServiceInternalDtoErrorResponse {
    return GithubComHoshinaDevTicketingServiceInternalDtoErrorResponseFromJSONTyped(json, false);
}

export function GithubComHoshinaDevTicketingServiceInternalDtoErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubComHoshinaDevTicketingServiceInternalDtoErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GithubComHoshinaDevTicketingServiceInternalDtoErrorResponseToJSON(json: any): GithubComHoshinaDevTicketingServiceInternalDtoErrorResponse {
    return GithubComHoshinaDevTicketingServiceInternalDtoErrorResponseToJSONTyped(json, false);
}

export function GithubComHoshinaDevTicketingServiceInternalDtoErrorResponseToJSONTyped(value?: GithubComHoshinaDevTicketingServiceInternalDtoErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

