/* tslint:disable */
/* eslint-disable */
/**
 * Ticketing Service API
 * Laboratory experiment ticketing service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequest
 */
export interface GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequest {
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequest
     */
    experimentTemplateId: string;
}

/**
 * Check if a given object implements the GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequest interface.
 */
export function instanceOfGithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequest(value: object): value is GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequest {
    if (!('experimentTemplateId' in value) || value['experimentTemplateId'] === undefined) return false;
    return true;
}

export function GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequestFromJSON(json: any): GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequest {
    return GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequestFromJSONTyped(json, false);
}

export function GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'experimentTemplateId': json['experiment_template_id'],
    };
}

export function GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequestToJSON(json: any): GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequest {
    return GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequestToJSONTyped(json, false);
}

export function GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequestToJSONTyped(value?: GithubComHoshinaDevTicketingServiceInternalDtoAddExperimentTemplateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'experiment_template_id': value['experimentTemplateId'],
    };
}

