/* tslint:disable */
/* eslint-disable */
/**
 * Ticketing Service API
 * Laboratory experiment ticketing service.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequest
 */
export interface GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequest
     */
    closedReason?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequest
     */
    status: string;
}

/**
 * Check if a given object implements the GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequest interface.
 */
export function instanceOfGithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequest(value: object): value is GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequest {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequestFromJSON(json: any): GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequest {
    return GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequestFromJSONTyped(json, false);
}

export function GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'closedReason': json['closed_reason'] == null ? undefined : json['closed_reason'],
        'status': json['status'],
    };
}

export function GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequestToJSON(json: any): GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequest {
    return GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequestToJSONTyped(json, false);
}

export function GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequestToJSONTyped(value?: GithubComHoshinaDevTicketingServiceInternalDtoTransitionStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'closed_reason': value['closedReason'],
        'status': value['status'],
    };
}

